"""`dpyr stubgen`: generate typed schema modules from data files (Epic 7).

    dpyr stubgen data/*.parquet -o dpyr_schemas.py

emits, per file, a `Cols` subclass with one typed attribute per column plus
a ready-made loader, so IDEs complete column names and column-typed
methods statically:

    from dpyr_schemas import starwars
    starwars.filter(lambda c: c.height > 180)   # c.height completes
"""

from __future__ import annotations

import argparse
import keyword
import re
import sys
from pathlib import Path

from . import dtypes as dt
from .dtypes import DType

_EXPR_CLASS = {
    dt.INT64: "NumExpr", dt.FLOAT64: "NumExpr", dt.BOOL: "BoolExpr",
    dt.STR: "StrExpr", dt.DATE: "TemporalExpr", dt.DATETIME: "TemporalExpr",
}


def _identifier(name: str) -> str:
    safe = re.sub(r"\W", "_", name)
    if not safe or safe[0].isdigit() or keyword.iskeyword(safe):
        safe = f"c_{safe}"
    return safe


def _schema_of(path: Path) -> dict[str, DType]:
    from .polars_backend import schema_from_polars
    import polars as pl
    if path.suffix == ".parquet":
        return schema_from_polars(pl.scan_parquet(path))
    if path.suffix == ".csv":
        return schema_from_polars(pl.scan_csv(path))
    raise SystemExit(f"stubgen: unsupported file type {path.suffix} ({path})")


def generate(paths: list[Path]) -> str:
    lines = [
        '"""Generated by `dpyr stubgen` — do not edit by hand."""',
        "",
        "from typing import cast",
        "",
        "from dpyr import DFrame, read_csv, read_parquet",
        "from dpyr.expr import BoolExpr, NumExpr, StrExpr, TemporalExpr",
        "from dpyr.frame import ColsProxy",
        "",
    ]
    for path in paths:
        schema = _schema_of(path)
        cls = _identifier(path.stem).title().replace("_", "") + "Cols"
        lines.append(f"class {cls}(ColsProxy):")
        for name, dtype in schema.items():
            lines.append(f"    {_identifier(name)}: {_EXPR_CLASS[dtype]}")
        reader = "read_parquet" if path.suffix == ".parquet" else "read_csv"
        var = _identifier(path.stem)
        lines += [
            "",
            "",
            f"def load_{var}() -> DFrame[{cls}]:",
            f"    return cast(DFrame[{cls}], {reader}({str(path)!r}))",
            "",
            "",
            f"{var}: DFrame[{cls}] = load_{var}()",
            "",
            "",
        ]
    return "\n".join(lines[:-1])


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(prog="dpyr")
    sub = parser.add_subparsers(dest="command", required=True)
    gen = sub.add_parser("stubgen", help="generate typed schema modules")
    gen.add_argument("files", nargs="+", type=Path)
    gen.add_argument("-o", "--output", type=Path, default=None,
                     help="output .py file (default: stdout)")
    args = parser.parse_args(argv)

    if args.command == "stubgen":
        code = generate(args.files)
        if args.output:
            args.output.write_text(code + "\n")
            print(f"wrote {args.output}", file=sys.stderr)
        else:
            print(code)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
